// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"golang-oauth-tutor/config"
	"golang-oauth-tutor/internal/controllers"
	"golang-oauth-tutor/internal/services"
)

// Injectors from wire.go:

func InitRedirectController() *controllers.RedirectController {
	googleOauthConfig := config.GoogleOauthConfigInit()
	oAuthService := services.NewOAuthService(googleOauthConfig)
	redirectController := controllers.NewRedirectController(oAuthService)
	return redirectController
}

// wire.go:

var oauthSet = wire.NewSet(config.GoogleOauthConfigInit)

var serviceSet = wire.NewSet(services.NewOAuthService)
